steps:
  - id: 'Running docker compose'
    name: 'gcr.io/$PROJECT_ID/docker-compose:${_DOCKER_COMPOSE_VERSION}'
    args: ['-f', 'docker-compose-ci.yml', 'up', '-d']
  
  - id: 'Running docker ps'
    name: 'gcr.io/cloud-builders/docker'
    arg: ['ps']
substitutions:
  _DOCKER_COMPOSE_VERSION: 1.26.2    
