steps:
  - id: "Running docker compose"
    name: 'gcr.io/$PROJECT_ID/docker-compose:${_DOCKER_COMPOSE_VERSION}'
    args: ['-f', 'docker-compose-ci.yml', 'up', '-d']
  
  - id: "Running docker ps"
    name: 'gcr.io/cloud-builders/docker'
    args: ['ps']

  - id: "Running composer"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-it', 'app', 'composer', 'install']

    - id: "Copying .env"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-it', 'app', 'cp', '.env.example', '.env']

    - id: "Running key:generate"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-it', 'app', 'php', '/var/www/artisan', 'key:generate']

    - id: "Running migrations"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-it', 'app', 'php', '/var/www/artisan', 'migrate']

    - id: "Running php unit"
    name: 'gcr.io/cloud-builders/docker'
    args: ['exec', '-it', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']
substitutions:
  _DOCKER_COMPOSE_VERSION: 1.26.2    
