steps:
  - id: "Running docker compose"
    name: "docker/compose"
    args: ['-f', 'docker-compose-ci.yml', 'up', '-d']

  - id: "Change /var/www owner"
    name: 'docker'
    args: ['exec','-u','root','-t','app','chown','-R','www-data:www-data','/var/www']

  - id: "Running composer"
    name: 'docker'
    args: ['exec', '-t', 'app', 'composer', 'install']

  - id: "Copying .env"
    name: 'docker'
    args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']

  - id: "Running key:generate"
    name: 'docker'
    args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate']

  - id: "Running migrations"
    name: 'docker'
    args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'migrate']

  - id: "Running PHP unit"
    name: 'docker'
    args: ['exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']

  - id : "Building image from Dockerfile.prod"
    name: docker
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/app-laravel:$SHORT_SHA', '-f', 'Dockerfile.prod', '.']

  - id: "Pushing Image"
    name: docker
    args: ['push', 'gcr.io/$PROJECT_ID/app-laravel:$SHORT_SHA']
substitutions:
  _DOCKER_COMPOSE_VERSION: 1.26.2    
