version: '3.7'

services:
  app:
    build: .
    container_name: app
#    environment:
#      - DB_HOST=db
#      - DB_DATABASE=laravel
#      - DB_USERNAME=root
#      - DB_PASSWORD=root
#    entrypoint: dockerize -template ./.docker/app/.env:.env -wait tcp://db:3306 -timeout 40s ./.docker/entrypoint.sh
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis
  nginx:
    build: .docker/nginx
    container_name: nginx
    environment:
      - NGINX_HOST_APPLICATION=app
      - NGINX_PORT_APPLICATION=9000
    entrypoint: dockerize -template /etc/nginx/conf.d/nginx.tmpl:/etc/nginx/conf.d/nginx.conf -wait tcp://app:9000 nginx -g "daemon off;"
    restart: unless-stopped
    tty: true
    ports:
      - "8000:80"
    volumes:
      - .:/var/www
    networks:
      - app-network
    depends_on:
      - app

  redis:
    image: library/redis:6.0.6-alpine
    expose:
      - 6379
    networks:
      - app-network

  db:
    build: .docker/mysql
    command: --innodb-use-native-aio=0
    container_name: db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    volumes:
    - ./.docker/dbdata:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=root
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
